# -*- coding: utf-8 -*-
"""Trabajadores

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SWJk40dL4hq9wosliFsXibAK9D85muES
"""

lista_empleados = []
#Convertimos la lista en un diccionario, ya que asi se facilita su uso.
trabajadores = {"Juan Pérez":0,"María García":0,"Carlos López":0,"Ana Martínez":0,"Pedro Rodríguez":0,"Laura Hernández":0,"Miguel Sánchez":0,"Isabel Gómez":0,"Francisco Díaz":0,"Elena Fernández":0}

def asignar():
  #Se les va asignando a las claves un valor aleatorio
  import random
  a = 300000
  b = 2500000
  for i in trabajadores:
   trabajadores[i] = random.randint(a,b)

  #Se guardan en una lista para facilitar su uso.
  lista_empleados.append(trabajadores)

def clasificar():
  #Con estos diccionarios se sabra la cantidad de trabajadores categorizados.
  lista_menor = {}
  lista_media = {}
  lista_mayor = {}
  #Aqui se van categotizando a los empleados, dependiendo de cuanto es su sueldo.
  for i in lista_empleados:
   for clave,valor in i.items():
    if valor<800000:
     lista_menor[clave] = valor
    elif valor >=800000 and valor<= 2000000:
     lista_media[clave] = valor
    elif valor > 2000000:
     lista_mayor[clave] = valor
  print("Sueldo menor a $800.000, total:",len(lista_menor))
  for clave,valor in lista_menor.items():
   print(f"""Nombre: {clave}
   Sueldo: {valor}""")
  print()
  print("Sueldo de entre $800.000 y $2.000.000, total:",len(lista_media))
  for clave,valor in lista_media.items():
   print(f"""Nombre: {clave}
   Sueldo: {valor}""")
  print()
  print("Sueldo superior a $2.000.000, total:",len(lista_mayor))
  for clave,valor in lista_mayor.items():
   print(f"""Nombre: {clave}
   Sueldo: {valor}""")
def estadistica():
  #Con estas variables se guardara el valor mas alto y mas bajo, incluyendo una lista donde se utilizara para obtener el sueldo promedio y media geometrica
  valor_alto = 0
  valor_bajo = 2500000
  sueldos = []
  #con las sentencias de decision se obtendran los valores mas altos y bajos.
  for i in lista_empleados:
   for clave,valor in i.items():
    sueldos.append(valor)
    if valor_alto < valor:
      valor_alto = valor
   if valor_bajo > valor:
    valor_bajo = valor
  #Aqui se obtiene el sueldo promedio, primero obteniendo el total, y despues dividiendolo.
  promedio = sum(sueldos)
  promedio //= len(sueldos)
  #Aqui se calcula la media geometrica.
  from scipy.stats import gmean
  Media_G = gmean(sueldos)
  print("Sueldo mas alto:",valor_alto)
  print("Sueldo mas bajo:",valor_bajo)
  print("Sueldo promedio:",promedio)
  print("Media geometrica:",int(Media_G))

def reporte():
  import csv
  num=0
  for i in lista_empleados:
   num += 1
   print(f"Empleado N°",num)
   for clave,valor in i.items():
    #Aqui se muestra el sueldo, los descuentos, y el sueldo liquido que queda, para de esta forma ser guardadas en un archivo csv.
     print(f"""{clave}
            Sueldo base: {valor}
            Descuento salud: {int(valor*0.07)}
            Descuento AFP: {int(valor*0.12)}
            Sueldo liquido: {valor-int(valor*0.07)-int(valor*0.12)}""")
 #Los datos, despues de ser calculados, se guardan.
  with open("Lista de trabajadores.csv",mode="w") as lista_trabajadores_csv:
    for i in lista_empleados:
     for clave,valor in i.items():
      lista_trabajadores_csv.write(f"nombre: {clave}, Sueldo base: {valor}, Descuento salud: {int(valor*0.07)}, Descuento AFP: {int(valor*0.12)}, Sueldo liquido: {valor-int(valor*0.07)-int(valor*0.12)}\n")
#Aqui se elige la opcion.
print("""Bienvenido, seleccione una opcion:
      1.Asignar sueldos aleatorios.
      2.Clasificar sueldos.
      3.Ver estadisticas.
      4.Reporte de sueldos.
      5.Salir del programa.""")
try:
 decision = int(input())
except:
 print("Por favor, ingrese un valor numerico")

while True:

 if decision == 1:
  asignar()

 elif decision == 2:
  clasificar()

 elif decision == 3:
  estadistica()

 elif decision == 4:
  reporte()
 elif decision == 5:
  print("Finalizando programa...\nMi nombre es Francisco Avello.\nRut 22.014.655-3")
  break
 #Aqui se elige una opcion ya estando dentro del ciclo.
 print("""Bienvenido, seleccione una opcion:
      1.Asignar sueldos aleatorios.
      2.Clasificar sueldos.
      3.Ver estadisticas.
      4.Reporte de sueldos.
      5.Salir del programa.""")
 try:
  decision = int(input())
 except:
  print("Por favor, ingrese un valor numerico")

import csv
#Opcionalmente puede comprobar si los datos cargan con exito.
with open("Lista de trabajadores.csv",mode="r") as lista_trabajadores_csv:
  lector_csv = csv.reader(lista_trabajadores_csv)
  for i in lector_csv:
   print(i)
   print()